name: "Mark's Diary"
favicon: null
layout_spectrum: 0.01590505405329168
typography_spectrum: 0.6215230610687286
title: "Mark's Diary"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-55878969-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.057590052019804716
  lightness: 0.4545169754419476
  saturation: 0.34215942840091884
  rhythmicContrast: 0.193979577627033
purpose: []
